#!/bin/bash -i

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16
#$ -o run_extract.stdout
#$ -e run_extract.stderr

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
module load sratoolkit
fastq-dump -I --split-files /projectnb/bf528/users/dreadlocks/project_2/samples/P0_1.sra -O /projectnb/bf528/users/dreadlocks/project_2/samples
echo "Job finished: $(date +%F)"
