#!/bin/bash

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# your commands here
module load samtools/samtools-0.1.19_gnu446 bowtie2 boost tophat
# module load samtools bowtie2 boost tophat

tophat
-r 200
-G /project/bf591/project_2/reference/annot/mm9.gtf
--segment-length=20
--segment-mismatches=1
--no-novel-juncs
-o P0_1_tophat
-p 16
/projectnb2/bf528/users/dreadlocks/project_2/samples/P0_1_1.fastq
/projectnb2/bf528/users/dreadlocks/project_2/samples/P0_1_2.fastq

echo "Job finished: $(date +%F)"
